---
- name: check if helmfile is installed
  shell: which helmfile && helmfile --version | grep "^{{helmfile_version}}$"
  register: helmfile_is_installed
  failed_when: false
  changed_when: false

- name: install helmfile
  get_url:
    url: https://github.com/roboll/helmfile/releases/download/{{ helmfile_version }}/helmfile_linux_amd64
    dest: /usr/local/bin/helmfile
    mode: 0755
  become: true
  when: helmfile_is_installed.rc != 0

- name: check if helm diff plugin is installed
  shell: helm plugin list | grep diff
  register: helm_diff_is_installed
  failed_when: false
  changed_when: false

- name: install helmfile
  command: helm plugin install https://github.com/databus23/helm-diff --version master
  when: helm_diff_is_installed.rc != 0
