- name: install xclip dependencies
  apt:
    name: xclip
    state: present
  become: true

- name: add paste snippet
  lineinfile:
    path: ~/.bashrc
    state: present
    line: "{{ item }}"
  loop:
    - 'alias c=xclip'
    - 'alias "v=xclip -o"'
