---
- name: check if fzf is installed
  shell: which fzf
  register: fzf_is_installed
  failed_when: false
  changed_when: false

- name: install fzf
  command: go get -u github.com/junegunn/fzf
  when: fzf_is_installed.rc != 0
