---
- name: check if google-chrome is installed
  shell: dpkg-query -W -f='${Status}' google-chrome-stable | grep 'install ok installed'
  register: chrome_is_installed
  failed_when: false
  changed_when: false

- name: Install google-chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    state: present
  become: true
  when: chrome_is_installed.rc != 0

